
-- Generated by ORDS REST Data Services 19.4.6.r1421859
-- Schema: DEVELOPER  Date: Thu Jul 16 02:56:12 2020 
--

DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'DEVELOPER',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'developer',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'clinicAPI',
      p_base_path      => '/clinicAPI/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'clinicAPI',
      p_pattern        => 'pediatrician',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'clinicAPI',
      p_pattern        => 'pediatrician',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website from developer.clinic where pediatrics = ''TRUE'' OR family = ''TRUE''');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'clinicAPI',
      p_pattern        => 'speciality/:speciality_type',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'clinicAPI',
      p_pattern        => 'speciality/:speciality_type',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website from developer.clinic where INSTR(specialties_list, :speciality_type) > 0');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'clinicAPI',
      p_pattern        => 'primary',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => 'select * from clinic',
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'clinicAPI',
      p_pattern        => 'primary',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website from developer.clinic where adult = ''TRUE'' OR family = ''TRUE''');

  ORDS.DEFINE_MODULE(
      p_module_name    => 'hours',
      p_base_path      => '/hours/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'hours',
      p_pattern        => 'Monday',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'hours',
      p_pattern        => 'Monday',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website, to_char(to_date(MON_OPEN, ''HH:MI:SS AM''), ''HH:MI AM'') as open, 
    to_char(to_date(MON_CLOSE, ''HH:MI:SS PM''), ''HH:MI PM'') as close from developer.clinic
where MON_OPEN != ''0'' 
    and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') >= to_date(MON_OPEN,''HH:MI:SS AM'')
    and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') <= to_date(MON_CLOSE,''HH:MI:SS AM'')');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'hours',
      p_pattern        => 'Thursday',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'hours',
      p_pattern        => 'Thursday',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website, to_char(to_date(THURS_OPEN, ''HH:MI:SS AM''), ''HH:MI AM'') as open, 
    to_char(to_date(THURS_CLOSE, ''HH:MI:SS PM''), ''HH:MI PM'') as close from developer.clinic
where THURS_OPEN != ''0'' 
    and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') >= to_date(THURS_OPEN,''HH:MI:SS AM'')
    and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') <= to_date(THURS_CLOSE,''HH:MI:SS AM'')');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'hours',
      p_pattern        => 'Saturday',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'hours',
      p_pattern        => 'Saturday',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website, to_char(to_date(SAT_OPEN, ''HH:MI:SS AM''), ''HH:MI AM'') as open, 
    to_char(to_date(SAT_CLOSE, ''HH:MI:SS PM''), ''HH:MI PM'') as close from developer.clinic
where SAT_OPEN != ''0'' 
    and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') >= to_date(SAT_OPEN,''HH:MI:SS AM'')
    and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') <= to_date(SAT_CLOSE,''HH:MI:SS AM'')');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'hours',
      p_pattern        => 'Sunday',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'hours',
      p_pattern        => 'Sunday',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website, to_char(to_date(SUN_OPEN, ''HH:MI:SS AM''), ''HH:MI AM'') as open, 
    to_char(to_date(SUN_CLOSE, ''HH:MI:SS PM''), ''HH:MI PM'') as close from developer.clinic
where SUN_OPEN != ''0'' 
    and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') >= to_date(SUN_OPEN,''HH:MI:SS AM'')
    and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') <= to_date(SUN_CLOSE,''HH:MI:SS AM'')');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'hours',
      p_pattern        => 'Friday',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'hours',
      p_pattern        => 'Friday',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website, to_char(to_date(FRI_OPEN, ''HH:MI:SS AM''), ''HH:MI AM'') as open, 
    to_char(to_date(FRI_CLOSE, ''HH:MI:SS PM''), ''HH:MI PM'') as close from developer.clinic
where FRI_OPEN != ''0'' 
    and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') >= to_date(FRI_OPEN,''HH:MI:SS AM'')
    and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') <= to_date(FRI_CLOSE,''HH:MI:SS AM'')');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'hours',
      p_pattern        => 'Tuesday',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'hours',
      p_pattern        => 'Tuesday',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website, to_char(to_date(TUES_OPEN, ''HH:MI:SS AM''), ''HH:MI AM'') as open, 
    to_char(to_date(TUES_CLOSE, ''HH:MI:SS PM''), ''HH:MI PM'') as close from developer.clinic
    where TUES_OPEN != ''0'' 
        and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') >= to_date(TUES_OPEN,''HH:MI:SS AM'')
        and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') <= to_date(TUES_CLOSE,''HH:MI:SS AM'')');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'hours',
      p_pattern        => 'Wednesday',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'hours',
      p_pattern        => 'Wednesday',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website, to_char(to_date(WED_OPEN, ''HH:MI:SS AM''), ''HH:MI AM'') as open, 
    to_char(to_date(WED_CLOSE, ''HH:MI:SS PM''), ''HH:MI PM'') as close from developer.clinic
where WED_OPEN != ''0'' 
    and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') >= to_date(WED_OPEN,''HH:MI:SS AM'')
    and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') <= to_date(WED_CLOSE,''HH:MI:SS AM'')');

  ORDS.DEFINE_MODULE(
      p_module_name    => 'oracle.example.hr',
      p_base_path      => '/hr/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'empsec/:empname',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'empsec/:empname',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page => 25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select empno, ename, deptno, job from emp 
	where ((select job from emp where ename = :empname) IN (''PRESIDENT'', ''MANAGER'')) 
    OR  
    (deptno = (select deptno from emp where ename = :empname)) 
order by deptno, ename
');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'empsecformat/:empname',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'empsecformat/:empname',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
  prevdeptno     number;
  total_rows     number;
  deptloc        varchar2(20);
  deptname       varchar2(20);
  
  CURSOR         getemps is select * from emp 
                             start with ename = :empname
                           connect by prior empno = mgr
                             order siblings by deptno, ename;
BEGIN
  sys.htp.htmlopen;
  sys.htp.headopen;
  sys.htp.title(''Hierarchical Department Report for Employee ''||apex_escape.html(:empname));
  sys.htp.headclose;
  sys.htp.bodyopen;
 
  for l_employee in getemps 
  loop
      if l_employee.deptno != prevdeptno or prevdeptno is null then
          select dname, loc 
            into deptname, deptloc 
            from dept 
           where deptno = l_employee.deptno;
           
          if prevdeptno is not null then
              sys.htp.print(''</ul>'');
          end if;

          sys.htp.print(''Department '' || apex_escape.html(deptname) || '' located in '' || apex_escape.html(deptloc) || ''<p/>'');
          sys.htp.print(''<ul>'');
      end if;

      sys.htp.print(''<li>'' || apex_escape.html(l_employee.ename) || '', ''  || apex_escape.html(l_employee.empno) || '', '' || 
                        apex_escape.html(l_employee.job) || '', '' || apex_escape.html(l_employee.sal) || ''</li>'');

      prevdeptno := l_employee.deptno;
      total_rows := getemps%ROWCOUNT;
      
  end loop;

  if total_rows > 0 then
      sys.htp.print(''</ul>'');
  end if;

  sys.htp.bodyclose;
  sys.htp.htmlclose;
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'employees/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'employees/',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page => 7,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select empno "$uri", rn, empno, ename, job, hiredate, mgr, sal, comm, deptno
  from (
       select emp.*
            , row_number() over (order by empno) rn
         from emp
       ) tmp');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'version/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'version/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin 
 sys.htp.p(''{"version": "19.2"}'');
end;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'employees/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'employees/:id',
      p_method         => 'GET',
      p_source_type    => 'json/query;type=single',
      p_items_per_page => 25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from emp 
where empno = :id');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'employees/:id',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
    update emp set ename = :ename, job = :job, hiredate = :hiredate, mgr = :mgr, sal = :sal, comm = :comm, deptno = :deptno
    where empno = :id;
    :status := 200;
    :location := :id;
exception
    when others then
        :status := 400;
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.example.hr',
      p_pattern            => 'employees/:id',
      p_method             => 'PUT',
      p_name               => 'X-APEX-FORWARD',
      p_bind_variable_name => 'location',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.example.hr',
      p_pattern            => 'employees/:id',
      p_method             => 'PUT',
      p_name               => 'ID',
      p_bind_variable_name => 'id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.example.hr',
      p_pattern            => 'employees/:id',
      p_method             => 'PUT',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'empinfo/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'empinfo/',
      p_method         => 'GET',
      p_source_type    => 'csv/query',
      p_items_per_page => 25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from emp');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'employeesfeed/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'employeesfeed/',
      p_method         => 'GET',
      p_source_type    => 'json/query;type=feed',
      p_items_per_page => 25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select empno, ename from emp order by deptno, ename');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'employeesfeed/:id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.example.hr',
      p_pattern        => 'employeesfeed/:id',
      p_method         => 'GET',
      p_source_type    => 'csv/query',
      p_items_per_page => 25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from emp where empno = :id');

  ORDS.DEFINE_MODULE(
      p_module_name    => 'walkin',
      p_base_path      => '/walkin/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'walkin',
      p_pattern        => 'Tuesday',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'walkin',
      p_pattern        => 'Tuesday',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website, to_char(to_date(walk_in_tues_open, ''HH:MI:SS AM''), ''HH:MI AM'') as open, 
    to_char(to_date(walk_in_tues_close, ''HH:MI:SS PM''), ''HH:MI PM'') as close from developer.clinic
where walk_in_tues_open is not null
and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') <= to_date(walk_in_tues_close,''HH:MI:SS PM'') 
and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') >= to_date(walk_in_tues_open,''HH:MI:SS AM'')');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'walkin',
      p_pattern        => 'Monday',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'walkin',
      p_pattern        => 'Monday',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website, to_char(to_date(walk_in_mon_open, ''HH:MI:SS AM''), ''HH:MI AM'') as open, 
    to_char(to_date(walk_in_mon_close, ''HH:MI:SS PM''), ''HH:MI PM'') as close from developer.clinic
where walk_in_mon_open is not null
and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') <= to_date(walk_in_mon_close,''HH:MI:SS PM'') 
and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') >= to_date(walk_in_mon_open,''HH:MI:SS AM'')
');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'walkin',
      p_pattern        => 'Wednesday',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'walkin',
      p_pattern        => 'Wednesday',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website, to_char(to_date(walk_in_wed_open, ''HH:MI:SS AM''), ''HH:MI AM'') as open, 
    to_char(to_date(walk_in_wed_close, ''HH:MI:SS PM''), ''HH:MI PM'') as close from developer.clinic
where walk_in_wed_open is not null
and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') <= to_date(walk_in_wed_close,''HH:MI:SS PM'') 
and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') >= to_date(walk_in_wed_open,''HH:MI:SS AM'')');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'walkin',
      p_pattern        => 'Thursday',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'walkin',
      p_pattern        => 'Thursday',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website, to_char(to_date(walk_in_thurs_open, ''HH:MI:SS AM''), ''HH:MI AM'') as open, 
    to_char(to_date(walk_in_thurs_close, ''HH:MI:SS PM''), ''HH:MI PM'') as close from developer.clinic
where walk_in_thurs_open is not null
and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') <= to_date(walk_in_thurs_close,''HH:MI:SS PM'') 
and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') >= to_date(walk_in_thurs_open,''HH:MI:SS AM'')');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'walkin',
      p_pattern        => 'Friday',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'walkin',
      p_pattern        => 'Friday',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website, to_char(to_date(walk_in_fri_open, ''HH:MI:SS AM''), ''HH:MI AM'') as open, 
    to_char(to_date(walk_in_fri_close, ''HH:MI:SS PM''), ''HH:MI PM'') as close from developer.clinic
where walk_in_fri_open is not null
and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') <= to_date(walk_in_fri_close,''HH:MI:SS PM'') 
and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') >= to_date(walk_in_fri_open,''HH:MI:SS AM'')');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'walkin',
      p_pattern        => 'Saturday',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'walkin',
      p_pattern        => 'Saturday',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website, to_char(to_date(walk_in_sat_open, ''HH:MI:SS AM''), ''HH:MI AM'') as open, 
    to_char(to_date(walk_in_sat_close, ''HH:MI:SS PM''), ''HH:MI PM'') as close from developer.clinic
where walk_in_sat_open is not null
and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') <= to_date(walk_in_sat_close,''HH:MI:SS PM'') 
and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') >= to_date(walk_in_sat_open,''HH:MI:SS AM'')');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'walkin',
      p_pattern        => 'Sunday',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'walkin',
      p_pattern        => 'Sunday',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select name, website, to_char(to_date(walk_in_sun_open, ''HH:MI:SS AM''), ''HH:MI AM'') as open, 
    to_char(to_date(walk_in_sun_close, ''HH:MI:SS PM''), ''HH:MI PM'') as close from developer.clinic
where walk_in_sun_open is not null
and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') <= to_date(walk_in_sun_close,''HH:MI:SS PM'') 
and to_date(TO_CHAR(current_timestamp - INTERVAL ''5'' HOUR,''hh24:mi:ss''), ''HH24:MI:SS'') >= to_date(walk_in_sun_open,''HH:MI:SS AM'')');

    
  ORDS.CREATE_ROLE(p_role_name => 'oracle.dbtools.role.autorest.developer');
    
  l_roles(1) := 'oracle.dbtools.autorest.any.schema';
  l_roles(2) := 'oracle.dbtools.role.autorest.developer';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.dbtools.autorest.privilege.developer',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => '',
      p_description    => '',
      p_comments       => NULL); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;
    
  l_roles(1) := 'SODA Developer';
  l_patterns(1) := '/soda/*';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.soda.privilege.developer',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => '',
      p_description    => '',
      p_comments       => NULL); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;
          
COMMIT;

END;